apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: github-iac-manifests
spec:
  # Create a secret that contains age's private key:
  #
  # kubectl create secret generic \
  #   --namespace default \
  #   --from-literal identity.agekey=yourkey \
  #   github-iac-manifests-age-key
  decryption:
    provider: sops
    secretRef:
      name: github-iac-manifests-age-key
  # Too many times I accidentally deleted my persistent volumes.
  deletionPolicy: Orphan
  interval: 5m
  path: kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: github-iac-manifests
    namespace: default
